### ISSUE TITLE
StackOverflowError on double-rep0

### ISSUE THREAD

**Issue by kubukoz** [nrinaudo/kantan.parsers#4]
Hi! I was trying to use the library (`1.0.10`), and I bumped into this:

```scala
Parser.char('a').rep0.rep0.parse("")
```

throwing:

```
java.lang.StackOverflowError
	at kantan.parsers.Message$.empty(Message.scala:56)
	at kantan.parsers.TokenParser.rep$$anonfun$1(TokenParser.scala:65)
	at kantan.parsers.Parser.flatMap$$anonfun$1(Parser.scala:157)
	at kantan.parsers.Parser.$bar$$anonfun$1(Parser.scala:198)
	at kantan.parsers.Parser.map$$anonfun$1(Parser.scala:141)
	at kantan.parsers.Parser.flatMap$$anonfun$1(Parser.scala:159)
	at kantan.parsers.Parser.$bar$$anonfun$1(Parser.scala:198)
	at kantan.parsers.Parser.map$$anonfun$1(Parser.scala:141)
	at kantan.parsers.Parser.flatMap$$anonfun$1(Parser.scala:159)
	at kantan.parsers.Parser.$bar$$anonfun$1(Parser.scala:198)
	at kantan.parsers.Parser.map$$anonfun$1(Parser.scala:141)
```

To be clear, this is minimized from a bigger example, which made more sense:

```scala
val keywordParser =
  Parser.string("let").as(Token.Let) |
    Parser.string("=").as(Token.Equals)

val tokenParser: Parser[Char, Token] =
  keywordParser |
    Parser.whitespace.rep0.map(_.mkString).map(Token.Whitespace(_))

val tokenStreamParser = tokenParser.rep0 *> Parser.end
tokenStreamParser.parse("let let").toEither
```

which also throws an SOO.

**Comment by kubukoz** [comment]
here's another one: `Parser.char('a').?.rep.parse("")`

**Comment by nrinaudo** [comment]
Well, it makes sense, right? It’s either that or an infinite loop. You’re asking for an infinite repetition of potentially empty strings. The empty string matches a?, and then repeats forver.

I believe this is why cats-parse has Parser0 and Parser1, to check for such cases at compile time at the cost of a clunkier (in my opinion) API. Always the same trade off: the more you check at compile time, the more cumbersome your libs. It’s just a matter of finding the comfort to correctness ratio you’re happy with.

Or am I missing something?

**Comment by kubukoz** [comment]
I guess it makes sense that the parser fails, but I don't think it should result in a SOO, but rather something custom - it's currently difficult to know what the user is doing wrong when such a thing happens.
